name: awake
favicon: null
layout_spectrum: 0.6452631780412048
typography_spectrum: 0.8863157632295042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b1521'
    - '#ffffff'
    - '#055a79'
    - '#a7a7ab'
    - '#6e6e74'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
